# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\xba\x01\n\nP2PMessage\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.P2PMessage.MessageType\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\r\n\x05nonce\x18\x03 \x01(\x0c\x12\x10\n\x08hmac_tag\x18\x04 \x01(\x0c\"S\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bRSA_PUB_KEY\x10\x01\x12\x14\n\x10\x41\x45S_KEY_EXCHANGE\x10\x02\x12\x10\n\x0c\x43HAT_MESSAGE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_P2PMESSAGE']._serialized_start=18
  _globals['_P2PMESSAGE']._serialized_end=204
  _globals['_P2PMESSAGE_MESSAGETYPE']._serialized_start=121
  _globals['_P2PMESSAGE_MESSAGETYPE']._serialized_end=204
# @@protoc_insertion_point(module_scope)
